- name: pre-download the required master containers
  shell: kubeadm config images pull
  become: true
  when: "'k8s_masters' in group_names"

- name: configure the first Kubernetes master
  include: masters-first.yml
  when: "inventory_hostname == groups['k8s_masters'][0]"

